apiVersion: apps/v1
kind: Deployment
metadata:
  name: timeoffapp
  namespace: default
  labels:
    app: timeoffapp
spec:
  replicas: 3
  minReadySeconds: 45
  selector:
    matchLabels:
      app: timeoffapp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: timeoffapp
    spec:
      containers:
        - image: us-east1-docker.pkg.dev/devops-challenge-357700/dockerchallenge/timeoffapp:latest
          imagePullPolicy: Always
          name: timeoffapp
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 100m
              memory: 1Gi
            limits:
              cpu: 300m
              memory: 1.5Gi
      restartPolicy: Always
      imagePullSecrets:
        - name: gcrsecret
      terminationGracePeriodSeconds: 30