apiVersion: v1
kind: Service
metadata:
  labels: #PODS
    apps: timeoffapp
  name: timeoffapp
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: timeoffapp
  sessionAffinity: None