apiVersion: v1
kind: Service
metadata:
  labels: #PODS
    apps: sampleapp
  name: sampleapp
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: sampleapp
  sessionAffinity: None